name: 'test'
on:
  workflow_dispatch:

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "Build Changelog"
        id: github_release
        uses: ./
        with:
          configuration: "configs/configuration_repo.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Result
        run: |
          echo "${{steps.github_release.outputs.changelog}}"
      
