name: 'test'
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "Build Changelog"
        id: github_release
        uses: ./
        # with:
          # configuration: "configs/configuration.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Result
        run: |
          echo "${{steps.github_release.outputs.changelog}}"
      
